In [3]:
%pip install numpy

  Obtaining dependency information for numpy from https://files.pythonhosted.org/packages/c9/57/3cb8131a0e6d559501e088d3e685f4122e9ff9104c4b63e4dfd3a577b491/numpy-1.25.2-cp311-cp311-macosx_10_9_x86_64.whl.metadata
  Using cached numpy-1.25.2-cp311-cp311-macosx_10_9_x86_64.whl.metadata (5.6 kB)
Using cached numpy-1.25.2-cp311-cp311-macosx_10_9_x86_64.whl (20.8 MB)
Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np

In [5]:
a = np.array([20, 40, 60])
b = np.array([10, 20, 30])
c = np.array([5, 10, 15, 20])

In [6]:
# This is valid since both vectors have the same dimensionality 
a+b

array([30, 60, 90])

In [7]:
# the is invalid since both vectors do NOT have the same dimensionality 
a+c

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [8]:
a-b

array([10, 20, 30])

In [9]:
a*b

array([ 200,  800, 1800])

In [10]:
a/b

array([2., 2., 2.])

In [17]:
scalar = 2

In [13]:
list_a = [10,11,12,13,14,15]
print(list_a)

[10, 11, 12, 13, 14, 15]


In [14]:
list_as_array = np.array(list_a)
print(list_as_array)

[10 11 12 13 14 15]


In [20]:
# Scalar multiplication with vectors 
correct = scalar * list_as_array
incorrect = scalar * list_a

print(f'Correct: {correct}')
print(f'Incorrect: {incorrect}')

Correct: [20 22 24 26 28 30]
Incorrect: [10, 11, 12, 13, 14, 15, 10, 11, 12, 13, 14, 15]


In [ ]:
# Vector Addition
# ==============================================
# Adding 2 vectors traverses from the tail of the first vector to the head of the second vector 

# Vector Subtraction 
# ==============================================
# Subtracting 2 vectors requires translating the vectors such that their tails are at the same coordinates 
# The difference (subtraction) is the line (vector) that goes from the head of the negative vector to the head of the positive vector 

# Vector Multiplication
# ============================================== 
# Vector multiplication has 4 possible cases: 
# A: Scalar value is greater than 1 
# B: Scalar value is between 1 and 0 
# C: Scalar value is exactly 0 
# D: Scalar value is negative (less than 0)
# Only in case D (scalar value is negative) will the vector change direction
